### ISSUE TITLE
Try to use a device with profile A5-20-06, but ...

### ISSUE THREAD

**Issue by GerhardKreuzer** [ChristopheHD/HA_enoceanmqtt-addon#3] opened 2024-11-26 10:24 UTC
.. the log shows, that the device isn't detected. I get lot of datagrams, looks not that bad. What do I miss?

Here the log entries:

2024-11-26 08:17:16,636 INFO: received: 05:27:E3:1C->FF:FF:FF:FF (-45 dBm): 0x01 ['0xa5', '0x0', '0xa4', '0x2b', '0x2e', '0x5', '0x27', '0xe3', '0x1c', '0x80'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2024-11-26 08:17:16,637 INFO: unknown sensor: 05:27:E3:1C (RORG = 0xa5)
2024-11-26 09:17:16,251 INFO: received: 05:27:E3:1C->FF:FF:FF:FF (-52 dBm): 0x01 ['0xa5', '0x0', '0xa4', '0x2b', '0x2e', '0x5', '0x27', '0xe3', '0x1c', '0x80'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x34', '0x0'] OrderedDict()
2024-11-26 09:17:16,252 INFO: unknown sensor: 05:27:E3:1C (RORG = 0xa5)
2024-11-26 10:17:15,887 INFO: received: 05:27:E3:1C->FF:FF:FF:FF (-45 dBm): 0x01 ['0xa5', '0x0', '0xa4', '0x2b', '0x2e', '0x5', '0x27', '0xe3', '0x1c', '0x80'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2024-11-26 10:17:15,895 INFO: unknown sensor: 05:27:E3:1C (RORG = 0xa5)
2024-11-26 10:37:55,590 INFO: received: 05:27:E3:1C->FF:FF:FF:FF (-45 dBm): 0x01 ['0xd0', '0x9', '0x5', '0x27', '0xe3', '0x1c', '0x80'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2024-11-26 10:37:55,591 INFO: unknown sensor: 05:27:E3:1C (RORG = 0xd0)
2024-11-26 11:17:15,521 INFO: received: 05:27:E3:1C->FF:FF:FF:FF (-45 dBm): 0x01 ['0xa5', '0x0', '0xa4', '0x2b', '0x2e', '0x5', '0x27', '0xe3', '0x1c', '0x80'] ['0x0', '0xff', '0xff', '0xff', '0xff', '0x2d', '0x0'] OrderedDict()
2024-11-26 11:17:15,522 INFO: unknown sensor: 05:27:E3:1C (RORG = 0xa5)

With best regards

Gerhard

**Comment by ChristopheHD** [comment] 2024-11-26 13:53
Logs says your sensor is unknown, it means that the device is not defined in the "enoceanmqtt.devices" file.

**Comment by GerhardKreuzer** [comment] 2024-11-26 17:25
I know, but what to enter, documentation isn't very clear her.
I used:
[my_mva009]
address = 0x0527e31c # The address of valve in sleeping room
model   = micropelt/mva009
# sender  = 0xFFXXXXXX # base id of your EnOcean transceiver + unique offset
rorg = 0xA5
func = 0x20
type = 0x06
The sender ID is unknowen to me, maybe it is part of the data.
I asked micropelt, they produce this things, but no answer uptil now.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment] 2024-11-27 10:08
Hi,
tried it, but now the Add-On will not start anymore. I copied the text, so no typo. Is this really the correct seetting? What can happen to my file? I use 'Studio Code Serveer' for editing. Works well uptill now.
I also restarted every thing-
With best regards
Gerhard

**Comment by GerhardKreuzer** [comment] 2024-11-27 10:33
Some more log entries:
OR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/f93730fa_ha_enoceanmqtt_aseracorp/stats - Container addon_f93730fa_ha_enoceanmqtt_aseracorp is not running
2024-11-27 11:29:11.602 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/f93730fa_ha_enoceanmqtt_aseracorp/stats - Container addon_f93730fa_ha_enoceanmqtt_aseracorp is not running

No idea what I have done to kill it.

**Comment by GerhardKreuzer** [comment] 2024-11-27 10:54
0.1.30

**Comment by ChristopheHD** [comment] 2024-11-27 11:00
Can you start the addon and send the logs of the addon ?

**Comment by GerhardKreuzer** [comment] 2024-11-27 11:08
[f93730fa_ha_enoceanmqtt_aseracorp_2024-11-27T11-06-14.481Z.log](https://github.com/user-attachments/files/17933324/f93730fa_ha_enoceanmqtt_aseracorp_2024-11-27T11-06-14.481Z.log)
... I see that the deevice config file is missing, but I don't belive this message, I just made thee changes you send me ... I don't deeleete or move something.

**Comment by ChristopheHD** [comment] 2024-11-27 11:11
Have you checked that the config file is there using the HA file editor addon ?

**Comment by GerhardKreuzer** [comment] 2024-11-27 11:15
I use 'Studio Code Server', here the file is there
How can I do another check?

**Comment by GerhardKreuzer** [comment] 2024-11-27 11:20
![grafik](https://github.com/user-attachments/assets/f0fac6c1-64c6-4374-ab2e-6b62162b8f40)

**Comment by GerhardKreuzer** [comment] 2024-11-27 11:20
Is this ok?

**Comment by GerhardKreuzer** [comment] 2024-11-27 12:39
/config/enoceanmqtt.devices
Ha, faound a 'Copy path' menue entry, so now we can be sure, the path is ok, isn't it?

**Comment by GerhardKreuzer** [comment] 2024-11-27 13:15
![grafik](https://github.com/user-attachments/assets/c157194b-4710-4fb5-b482-656eb97a8aca)
Now a samba share with the samba addon, looks also fine

**Comment by ChristopheHD** [comment] 2024-11-27 15:50
I reproduced the issue on my side, it's because I'm working on continuous integration.

**Comment by ChristopheHD** [comment] 2024-11-27 16:50
Corrected in the last version (0.1.31). You may need to remove and reinstall the addon.

**Comment by GerhardKreuzer** [comment] 2024-11-27 16:55
Thanks, will give it a try

**Comment by GerhardKreuzer** [comment] 2024-11-27 17:16
Hmmmmm ...
![grafik](https://github.com/user-attachments/assets/3fca88a1-798c-4fe4-9865-1df187fcce16)
Is thee newest version
And looks like that it is running.
![grafik](https://github.com/user-attachments/assets/6f660fa4-5e21-4d73-a0ea-3adca7e0fffb)

But protocol looks similar.
I do a restart of HA (not the quick one).
The 'old' files weere still here.
I deinstalled V0.1.30.

How should I proceed?

**Comment by GerhardKreuzer** [comment] 2024-11-27 18:38
Made a new try. Deinstalled the AddOn, option 'delete files', but the .log remains. I deleted it manually via my new samba share and restarted HA. New installation, configuration was lost, so new input and start, no chance, sorry.

With best reegards

Gerhard

**Comment by ChristopheHD** [comment] 2024-11-27 19:43
With worked for me:
* Removed the add on
* Check for addon updates (this reload the configuration file of the addon)
* Install the addon in the latest version 0.1.31
* Set the configuration of the addon
* Start the addon

No need to remove configuration files during this process.
Christophe

**Comment by GerhardKreuzer** [comment] 2024-11-27 20:05
Her the results:
![grafik](https://github.com/user-attachments/assets/de86e8f4-ca29-4960-a0c5-04b7029ab0de)
![grafik](https://github.com/user-attachments/assets/d184b6d1-47c4-4bcb-b98b-bd37376a9e71)
Now the new installation
![grafik](https://github.com/user-attachments/assets/9d0f8946-68df-426c-a8ed-2ea3219c0deb)
![grafik](https://github.com/user-attachments/assets/79c73828-4061-4d99-b36d-28b8a3b365d7)
No 'Search for updates here
After a while
![grafik](https://github.com/user-attachments/assets/5b1759ef-432c-4dbc-ba18-792e33bce3b4)
Now, starting config
![grafik](https://github.com/user-attachments/assets/03d7a4a8-3a05-4b41-9852-b38e310f0b80)
Name of the device-file, USB300 EnOcean stick and using the Mosqitto Broker from HA, and this component is running, no errors reported in the log.
And now **before** starting, I went on to 'Protocol' and see the old entries. Ok?
![grafik](https://github.com/user-attachments/assets/58bcf6c6-3ad4-4076-9d00-6234d40ab257)
After 'Start' I immediately switch to 'Protocol' and see the above text running ... so same entries, but new ones.
Than the AddOn stops.
Sorry, no idea what I do wrong here.

With best regards

Gerhard

**Comment by ChristopheHD** [comment] 2024-11-28 08:20
> Sorry, no idea what I do wrong here.
It's not you, it's me :) I did many changes this weeks and some have broken things.

I created a version 0.1.32 which should repair the update process. You can force search of update by going into the addon shop and clicking in the upper right menu.

**Comment by GerhardKreuzer** [comment] 2024-11-28 09:19
Hi ChristopheHD,
looks fine. Start playing ...
![grafik](https://github.com/user-attachments/assets/223305b1-4a1d-4bf7-861e-e20f8ce03935)

With best regards
Gerhard

**Comment by ChristopheHD** [comment] 2024-11-28 09:25
Good news !
I keep the issue opened and will close it as soon as I have corrected the wiki about model and EEP configuration.

**Comment by GerhardKreuzer** [comment] 2024-11-28 10:01
Finee, Thank you

**Comment by ChristopheHD** [comment] 2024-11-28 15:50
Wiki have been migrated to this repository and updated. The usage page now explains the difference between EEP and model configuration. Can you confirm it's more clear with this new description ?

**Closed** 2024-12-03 08:09 UTC
Labels: documentation, good first issue
